# VA-11 HALL-A

[General]
scale = 1.0
enable-animations = true
animated-background-placeholder = valhalla.png
background-fill-mode = fill

[LockScreen]
display = true
padding-top = 0
padding-right = 630
padding-bottom = 1006
padding-left = 0
background = valhalla.mp4
use-background-color = false
background-color = #000000
blur = 0
brightness = 0.0
saturation = 0.0

[LockScreen.Clock]
display = true
position = bottom-right
align = center
format = hh:mm
font-family = CyberpunkWaifus
font-size = 40
font-weight = 900
color = #FFFFFF

[LockScreen.Date]
display = true
format = dddd, MMMM dd, yyyy
locale = "en_US"
font-family = CyberpunkWaifus
font-size = 20
font-weight = 600
color = #FFFFFF
margin-top = 0

[LockScreen.Message]
font-size = 40
text=‎
icon = NewGame.png
icon-size = 1920
paint-icon = true
spacing = -1480

[LoginScreen]
background = valhalla.mp4
use-background-color = false
background-color = #000000
blur = 0
brightness = 0.0
saturation = 0.0

[LoginScreen.LoginArea]
position = left
margin = 260

[LoginScreen.LoginArea.Avatar]
shape = square
border-radius = 3000
active-size = 1
inactive-size = 3
inactive-opacity = 0
active-border-size = 3
inactive-border-size = 3
active-border-color = #FFFFFF
inactive-border-color = #FFFFFF

[LoginScreen.LoginArea.Username]
font-family = CyberpunkWaifus
font-size = 1
font-weight = 700
color = #000000
margin = 100

[LoginScreen.LoginArea.PasswordInput]
width = 300
height = 90
#display-icon = true
font-family = CyberpunkWaifus
font-size = 45
icon = blankpng.png
icon-size = 0
content-color = #FFFFFF
margin-top = 652

[LoginScreen.LoginArea.LoginButton]
icon = version.png
icon-size = 3185
margin-left = 120
hide-if-not-needed = false

[LoginScreen.LoginArea.Spinner]
display-text = true
text = "Loading..."
font-family = CyberpunkWaifus
font-weight = 600
font-size = 45
icon-size = 90
icon = blankpng.png
color = #FFFFFF
spacing = 0

[LoginScreen.LoginArea.WarningMessage]
font-family = CyberpunkWaifus
font-size = 20
font-weight = 400
normal-color = #FFFFFF
warning-color = #FFFFFF
error-color = #FFFFFF
margin-top = 10

[LoginScreen.MenuArea.Buttons]
font-family = CyberpunkWaifus
margin-right = 10
size = 60

[LoginScreen.MenuArea.Popups]
max-height = 500
item-height = 30
display-scrollbar = false
background-color = #000000
background-opacity = 1.0
active-option-background-color = #000000
active-option-background-opacity = 1.0
content-color = #FFFFFF
active-content-color = #FFFFFF
font-family = CyberpunkWaifus
font-size = 12
